server:
  port: 8090

mybatis:
  mapper-locations: mybatis-mapper/**/*.xml
  type-aliases-package: com.koreait.facebook

spring:
  thymeleaf:
#    prefix : classpath:templates/
#    suffix : .html
#    mode: HTML
    cache : false
#    check-template: true
  oauth2:
    client:
      registration:
        google:
          client-id: 386614050316-bk472t7nvctllv8jgr479ptde916qji2.apps.googleusercontent.com
          client-secret: iZpNWtYvdA827sUrtFPZowXS
          scope:
            - profile
            - email
        facebook:
          client-id: 166068028896823
          client-secret: b6ad01d4e4f70a561fb3b65f6de783e3
          scope:
            - email
            - public_profile
        kakao:
          authorization-grant-type: authorization_code
          client-id: c8c2eb353479ec0dcab44444610489f0
          client-secret: X0DNMUsl2eqYSTO3gU1EszKBQgskbap7
          redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
          scope:
            - profile_nickname
            - profile_image
          client-authentication-method: POST
          client-name: Kakao
        naver:
          authorization-grant-type: authorization_code
          client-id: HUlPJQ3woHNacSAPETZg
          client-secret: UDPdHO0ViQ
          redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
          scope: name,email,profile_image
          client-name: Naver

      provider:
        kakao:
          authorization-uri: https://kauth.kakao.com/oauth/authorize
          token-uri: https://kauth.kakao.com/oauth/token
          user-info-uri: https://kapi.kakao.com/v2/user/me
          user-name-attribute: properties
          # JSON 형태에서 "properties"라는 key값에 해당하는 value에 회원 정보가 담겨져있다.
        naver:
          authorization-uri: https://nid.naver.com/oauth2.0/authorize
          token-uri: https://nid.naver.com/oauth2.0/token
          user-info-uri: https://openapi.naver.com/v1/nid/me
          user-name-attribute: response
          # JSON 형태에서 "response"라는 key값에 해당하는 value에 회원 정보가 담겨져있다.

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://localhost:3306/facebook
    username: root
    password: root

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
      location: C:/springImg

  mail:
    host: smtp.gmail.com
    port: 587
    username: johyeonmin841@gmail.com
    password: zpjvoilqpcorlnmu
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000




