server:
  port: 8081

mybatis:
  mapper-locations: mapper/**/*.xml
  type-aliases-package: com.koreait.facebook

spring:
  thymeleaf:
#    prefix : classpath:templates/
#    suffix : .html
#    mode: HTML
    cache : false
#    check-template: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/facebook
    username: root
    password: koreait

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  mail:
    host: smtp.gmail.com
    port: 587
    username: johyeonmin841@gmail.com
    password: zpjvoilqpcorlnmu
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000